### ISSUE TITLE
Migracja do Pythona 3

### ISSUE THREAD

**Issue by michzimny** [emkael/deal-convert#1]
Jest jakaś motywacja za Pythonem 2? :)

np. https://github.com/emkael/deal-convert/blob/master/dealconvert/formats/stdout.py#L33

**Comment by emkael** [comment]
Zupełnie żadnej, w końcu główny skrypt też zaciąga `print_function` z `__future__`.

**Comment by michzimny** [comment]
To chyba z tej samej bajki (python 2):
https://github.com/emkael/deal-convert/blob/master/dealconvert/formats/pbn.py#L16
`TypeError: cannot use a string pattern on a bytes-like object`

/reopen :p

**Comment by emkael** [comment]
A, to już mi się przypomniało.
W mailach dawno temu pisałem, że zacząłem pisać pod Pythona 2, potem zacząłem pisać kompatybilność z 3 (stąd `__future__`), ale poległem na danych binarnych (`chr`/`ord` i tego typu atrakcje).

I stwierdziłeś, cytuję, "aha, python 2 raczej nie jest problemem" :P

**Comment by michzimny** [comment]
No trudno, to musimy przeżyć :P

**Comment by emkael** [comment]
Chyba się udało zmigrować to 3.x w sposób kompatybilny z 2.x
