### ISSUE TITLE
Na któryś format maszyna do powielania rzuca błędem

### ISSUE THREAD

**Issue by michzimny** [emkael/deal-convert#5]
W lipcowym TCG oraz od paru dniu w codziennych Pajączkach wydawane są pliki rozkładów wygenerowane ze źródłowego PBN za pomocą deal-convert. 

Pewna maszyna do powielania wyświetla dla tych rozkładów następujący błąd:
```
LINE TOO LONG
ERROR NO: 513 IN LINE: 2
```

Nie znamy jeszcze żadnych dodatkowych szczegółów, w szczególności typu pliku. Czekamy na odpowiedź użytkownika. @emkael, zostałeś podpięty do wątku w pewnej usłudze BS.

**Comment by emkael** [comment]
Wygenerowałem dwa zestawy plików: jeden BigDealem, wybierając wszystkie możliwe formaty, a drugi deal-converterem, konwertując na wszystkie możliwe formaty z oryginalnego PBNa.

Jedyna różnica to nagłówek pliku DLM, w którym podawana jest nazwa generatora.

Czekam na więcej informacji.

**Comment by michzimny** [comment]
Zrobię reopen, jak pojawią się jakieś szczegóły.

**Comment by michzimny** [comment]
Problem prawdopodobnie jest problemem z PBN, a więc błąd jest w innej części BS, nie w konwerterze.

**Comment by emkael** [comment]
W sumie trochę dziwne, że w takim razie tylko jedna maszyna się na tych plikach buntuje.

**Comment by michzimny** [comment]
Nie wiadomo. Niektórzy użytkownicy mogli nie zgłosić problemu albo go obejść, używając dla maszyny innych plików.
