### ISSUE TITLE
Wydruk PDF

### ISSUE THREAD

**Issue by emkael** [emkael/deal-convert#6]
Konwersja do pliku PDF z wydrukiem rozkładów.

**Comment by emkael** [comment]
e14ed77faac829aa4f2067b2081c6219c95d9305

**Comment by szymapa** [comment]
[wb200204.pdf](https://github.com/emkael/deal-convert/files/4162450/wb200204.pdf)

Wygenerowałem sobie z ciekawości pdfa.
Tabele nie podają jaki kontrakt idzie w trefle.
